version: '3.4'

services:
  carteirafinanceiradb:
    image: mongo

  carteirafinanceira:
    image: ${DOCKER_REGISTRY-}carteirafinanceira
    build:
      context: .
      dockerfile: CarteiraFinanceira/Dockerfile

volumes:
  mongo_data: